services:
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: CHANGE_PASSWORD
      MYSQL_USER: CHANGE_USERNAME
      MYSQL_PASSWORD: CHANGE_PASSWORD_FOR_MYSQL_USER
      TZ: "UTC"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
